# Generated by Django 2.2.6 on 2019-11-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('is_live_mode', models.BooleanField(blank=True, default=False)),
                ('live_publishable_key', models.CharField(default='', max_length=100)),
                ('live_secret_key', models.CharField(default='', max_length=100)),
                ('test_publishable_key', models.CharField(default='', max_length=100)),
                ('test_secret_key', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'StripeSetting',
                'verbose_name_plural': 'StripeSettings',
                'ordering': ('name', 'updated_at'),
                'managed': True,
                'unique_together': {('live_publishable_key',)},
            },
        ),
    ]
