# Generated by Django 2.2.6 on 2019-11-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalserversetting',
            name='callback_base_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
