# Generated by Django 2.2.6 on 2019-12-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
        ('rental', '0002_rentalserversetting_callback_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('station_sn', models.CharField(default='', max_length=32)),
                ('user_uuid', models.CharField(default='', max_length=128)),
                ('device_type', models.CharField(default='ios', max_length=10)),
                ('trade_no', models.CharField(default='', max_length=32)),
                ('slot_id', models.IntegerField(blank=True, default=-1)),
                ('power_bank_sn', models.CharField(default='', max_length=32)),
                ('fcm_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fcm_django.FCMDevice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RentalRequest',
                'verbose_name_plural': 'RentalRequest',
                'ordering': ('trade_no', 'updated_at'),
                'managed': True,
                'unique_together': {('trade_no',)},
            },
        ),
    ]
