# Generated by Django 2.2.6 on 2020-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rentalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='onesignal_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
