# Generated by Django 2.2.6 on 2020-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rentalrequest_onesignal_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalrequest',
            old_name='onesignal_token',
            new_name='onesignal_user_id',
        ),
        migrations.CreateModel(
            name='OneSignalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='', max_length=50)),
                ('user_auth_key', models.CharField(default='', max_length=256)),
                ('app_auth_key', models.CharField(default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OneSignalSetting',
                'verbose_name_plural': 'OneSignalSetting',
                'ordering': ('app_name', 'updated_at'),
                'managed': True,
                'unique_together': {('user_auth_key', 'app_auth_key')},
            },
        ),
    ]
