# Generated by Django 2.2.6 on 2020-02-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20200219_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='onesignalsetting',
            name='app_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='onesignalsetting',
            unique_together={('app_id', 'app_auth_key', 'user_auth_key')},
        ),
    ]
