# Generated by Django 2.2.6 on 2020-02-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_rentalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('REQUIRED_RENT', 'Required to rent a buttery'), ('RENTED', 'Rented a buttery'), ('RENTED', 'Required to return the buttery'), ('REQUIRED_RETURN', 'Returned the buttery')], default='REQUIRED_RENT', max_length=60),
        ),
    ]
