# Generated by Django 2.2.6 on 2020-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_auto_20200220_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='trade_no',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
