# Generated by Django 2.2.6 on 2020-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_auto_20200221_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalrequest',
            options={'managed': True, 'ordering': ('-trade_no', '-updated_at'), 'verbose_name': 'RentalRequest', 'verbose_name_plural': 'RentalRequest'},
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='trade_no',
            field=models.CharField(default='', max_length=32),
        ),
    ]
