# Generated by Django 2.2.6 on 2020-02-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_auto_20200221_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='fcm_device',
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('REQUIRED_RENT', 'Required to rent a buttery'), ('RENTED', 'Rented a buttery'), ('RENT_FAILED', 'Failed to rent'), ('RENTED', 'Required to return the buttery'), ('REQUIRED_RETURN', 'Returned the buttery')], default='REQUIRED_RENT', max_length=60),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='trade_no',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
