# Generated by Django 2.2.6 on 2020-02-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_auto_20200221_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalrequest',
            options={'managed': True, 'ordering': ('-updated_at',), 'verbose_name': 'RentalRequest', 'verbose_name_plural': 'RentalRequest'},
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('REQUIRED_RENT', 'Required to rent a buttery'), ('RENTED', 'Rented a buttery'), ('RENT_FAILED', 'Failed to rent'), ('RENTED', 'Required to return the buttery'), ('REQUIRED_RETURN', 'Returned the buttery'), ('RETURN_FAILED', 'Failed to retur the buttery')], default='REQUIRED_RENT', max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='rentalrequest',
            unique_together={('trade_no', 'station_sn')},
        ),
    ]
