# Generated by Django 2.2.6 on 2019-10-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mj_token', models.CharField(max_length=100)),
                ('from_title', models.CharField(max_length=100)),
                ('text_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SmsSetting',
                'verbose_name_plural': 'SmsSettings',
                'ordering': ('from_title', 'updated_at'),
                'managed': True,
                'unique_together': {('mj_token',)},
            },
        ),
        migrations.CreateModel(
            name='MailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=100)),
                ('from_email', models.CharField(max_length=200)),
                ('from_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('text_content', models.TextField(blank=True, default='')),
                ('html_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MailSetting',
                'verbose_name_plural': 'MailSettings',
                'ordering': ('from_email', 'updated_at'),
                'managed': True,
                'unique_together': {('api_key',)},
            },
        ),
    ]
