# Generated by Django 2.2.6 on 2019-10-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailjet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsetting',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='smssetting',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='api_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='from_email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='from_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='secret_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mailsetting',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='smssetting',
            name='from_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='smssetting',
            name='mj_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
