# Generated by Django 2.2.6 on 2019-10-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=100)),
                ('from_email', models.CharField(max_length=200)),
                ('from_name', models.CharField(max_length=200)),
                ('to_email', models.CharField(max_length=200)),
                ('to_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('text_content', models.TextField()),
                ('html_content', models.TextField()),
            ],
        ),
    ]
