# Generated by Django 2.2.6 on 2019-10-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailsetting',
            name='to_email',
        ),
        migrations.RemoveField(
            model_name='mailsetting',
            name='to_name',
        ),
    ]
